theme = "gruvbox"

[editor]
line-number = "relative"
auto-format = true
auto-pairs = true
cursorline = true
auto-completion = true
completion-trigger-len = 2
mouse = true
default-yank-register = "+"
clipboard-provider = "pasteboard"
scrolloff = 10
rulers = [100]
text-width = 100
idle-timeout = 250
true-color = true
popup-border = "all"
bufferline = "never"
color-modes = true
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "┊"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = false
display-messages = true
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true

[editor.whitespace]
characters = { tab = "»", space = "·", nbsp = "␣" }

# [editor.whitespace.render]
# space = "none"
# tab = "all"
# nbsp = "all"
# nnbsp = "all"
# newline = "none"

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "file-type",
  "position",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
]

[keys.normal]
x = "select_line_below"
A-x = "select_line_above"
g = { right = "goto_line_end", left = "goto_line_start" }
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]

# lazygit integration
C-g = [
  ":sh rm -f /tmp/helix-lazygit-open",
  ":new",
  ":insert-output sh -c 'HELIX_LAZYGIT_PARENT=1 HELIX_LAZYGIT_FILE=/tmp/helix-lazygit-open lazygit </dev/tty >/dev/tty; printf \"\\033[?1049h\\033[?2004h\" >/dev/tty' 2>/dev/null || true",
  ":buffer-close!",
  ":open %sh{cat /tmp/helix-lazygit-open}",
  ":set mouse false",                                                                                                               # First disable mouse to hint helix into activating it
  ":set mouse true",
  ":redraw",
  ":reload-all",
]

# --- yazi integration
space.e = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output sh -c 'yazi \"$1\" --chooser-file=/tmp/unique-file-u41ae14 </dev/tty >/dev/tty; printf \"\\033[?1049h\\033[?2004h\" >/dev/tty' sh '%{buffer_name}'",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":set mouse false",                                                             # First disable mouse to hint helix into activating it
  ":set mouse true",
  ":redraw",
]
space.E = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output sh -c 'yazi --chooser-file=/tmp/unique-file-h21a434 </dev/tty >/dev/tty; printf \"\\033[?1049h\\033[?2004h\" >/dev/tty'",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":set mouse false",                                            # First disable mouse to hint helix into activating it
  ":set mouse true",
  ":redraw",
]
# ---

esc = ["collapse_selection", "keep_primary_selection"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
G = "goto_file_end"
_ = "goto_first_nonwhitespace"
"ц" = "move_next_word_start" # w
"Ц" = "move_next_long_word_start" # W
"ф" = "append_mode" # a
"Ф" = "insert_at_line_end" # A
"п" = { "п" = "goto_file_start" } # gg
"П" = "goto_file_end" # G
"ч" = "extend_line_below"
"с" = "change_selection"

# qwerty
"м" = "select_mode"               # v
"ш" = "insert_mode"               # i
"Ш" = "insert_at_line_start"      # I
"и" = "move_prev_word_start"      # b
"И" = "move_prev_long_word_start" # B
"у" = "move_next_word_end"        # e
"У" = "move_next_long_word_end"   # E
"р" = "move_char_left"            # h
"о" = "move_visual_line_down"     # j
"О" = "join_selections"           # J
"л" = "move_visual_line_up"       # k
"д" = "move_char_right"           # l
"г" = "undo"
"Г" = "redo"
"н" = "yank"
"з" = "paste_after"
"З" = "paste_before"
"щ" = "open_below"
"Щ" = "open_above"

# uncolemak-dh
# "н" = "move_visual_line_down"
# "Н" = "join_selections"

# [keys.normal.space]
# # yazi
# e = [
#   ':sh rm -f /tmp/unique-file',
#   ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
#   ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
#   ':open %sh{cat /tmp/unique-file}',
#   ':redraw',
# ]
